markdown: kramdown
highlighter: pygments
permalink: /posts/:title

name: Ritesh Nadhani
url: http://psykidellic.github.io
description: something about everything
twitter: psykidellic
github: psykidellic
avatar: http://www.gravatar.com/avatar/f3e232c0016e12bb9ee2dcf23d5f2fd3
