markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Ritesh Nadhani
url: http://psykidellic.github.io
description: something about everything
twitter: psykidellic
github: psykidellic
avatar: images/holmes.png
#gravatar_url: http://localhost
#gravatar_url: http://gravatar.com/avatar/6f63cde8b16b035280ca615f621a6c8c
